### ISSUE TITLE
oureg table to word output

### ISSUE THREAD

**Issue by ghost** [BITSS/WorldBankApril2016#4]
Trying to use outreg2 to put table in word doc output. 
Tried:
             \input(./myfile.tex)
doesn't work at all
And:
             ![](./myfile.tex)
gives an image box but can't read the image

**Comment by garretchristensen** [comment]
@mjones5 @pythagoraswitch Hey there! It only took me a year+ to answer this, but I did! Yes, you can make a kind of dynamic doc with Word. Estout handles RTF output, and you can insert that as a link into a Word doc. So it's more like the two-step Stata+LaTeX combo than a one-step R Markdown or Stata-Markdoc solution, but it seems to work. Read through the "This is the paper.docx" file I put in my repo at https://github.com/BITSS/RT2Berkeley2017/tree/master/2-StataWord

**Comment by garretchristensen** [comment]
Ha! Literally on the day I figure this out, Stata 15 comes out, and has built-in support for Word!
http://www.stata.com/new-in-stata/create-word-documents/

**Comment by pythagoraswitch** [comment]
ha! that's pretty cool! DIME is teaching dynamic documents to RAs now (LaTeX), so I will notify this to the people.
